// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    OverflowMask: typeof import('./components/OverflowMask.vue')['default']
    QuestPost: typeof import('./components/QuestPost.vue')['default']
    QuestPostContent: typeof import('./components/QuestPostContent.vue')['default']
    QuestPostImage: typeof import('./components/QuestPostImage.vue')['default']
    QuestPostRefLink: typeof import('./components/QuestPostRefLink.vue')['default']
    QuestThreadPageContent: typeof import('./components/QuestThreadPageContent.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
