// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    GlobalHeader: typeof import('./components/layout/GlobalHeader.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    OverflowMask: typeof import('./components/misc/OverflowMask.vue')['default']
    QuestPost: typeof import('./components/QuestPost/QuestPost.vue')['default']
    QuestPostContent: typeof import('./components/QuestPost/QuestPostContent.vue')['default']
    QuestPostImage: typeof import('./components/QuestPost/QuestPostImage.vue')['default']
    QuestPostRefLink: typeof import('./components/QuestPost/QuestPostRefLink.vue')['default']
    QuestThreadPageContent: typeof import('./components/QuestThread/QuestThreadPageContent.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
