// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BarWithText: typeof import('./components/misc/BarWithText.vue')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    FixedWrapper: typeof import('./components/misc/FixedWrapper.vue')['default']
    GlobalHeader: typeof import('./components/layout/GlobalHeader.vue')['default']
    IonCaretDown: typeof import('~icons/ion/caret-down')['default']
    IonCaretUp: typeof import('~icons/ion/caret-up')['default']
    OverflowMask: typeof import('./components/misc/OverflowMask.vue')['default']
    PageLoadButton: typeof import('./components/misc/PageLoadButton.vue')['default']
    PageNumberControl: typeof import('./components/misc/PageNumberControl.vue')['default']
    PageNumberInput: typeof import('./components/misc/PageNumberInput.vue')['default']
    PhCaretDoubleDownBold: typeof import('~icons/ph/caret-double-down-bold')['default']
    PhCaretDoubleUpBold: typeof import('~icons/ph/caret-double-up-bold')['default']
    QuestPost: typeof import('./components/QuestPost/QuestPost.vue')['default']
    QuestPostContent: typeof import('./components/QuestPost/QuestPostContent.vue')['default']
    QuestPostFrame: typeof import('./components/QuestPost/QuestPostFrame.vue')['default']
    QuestPostImage: typeof import('./components/QuestPost/QuestPostImage.vue')['default']
    QuestPostLoader: typeof import('./components/QuestPost/QuestPostLoader.vue')['default']
    QuestPostRefLink: typeof import('./components/QuestPost/QuestPostRefLink.vue')['default']
    QuestThreadPageContent: typeof import('./components/QuestThread/QuestThreadPageContent.vue')['default']
    QuestThreadPageViewer: typeof import('./components/QuestThread/QuestThreadPageViewer.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
